### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Void-Syrex** [Anuken/CurseFilterPlugin#1]
The question about word filtering is whether the words of the old time will be affected? Or will it only affect our century? I want to clarify  censorship will be imposed on the full amount of the word(f*ck or bl**t) or by finding parts of the mat (such as fyuck or siyka)?

**Comment by Anuken** [comment]
It's a very simple filter. Only the whole word is filtered. Case is ignored.

If "heck" were marked as a swear word, then "h eck" and "h e c k" would **not** be filtered, but "hECK" should.
